language: cpp
compiler: gcc
os:
  - osx
  - linux
before_install:
  - echo $TRAVIS_OS_NAME
  #LINUX
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get update -qq; fi
install:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install -qq g++-4.9; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then export CXX="g++-4.9" CC="gcc-4.9"; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.9 90; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install cmake; fi
script:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then python fips build linux-make-release ; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then python fips build osx-xcode-release ; fi
  - python fips run test_asti
