version: 1.0.{build}
install:
- ps: wget https://s3.amazonaws.com/biibinaries/thirdparty/cmake-3.0.2-win32-x86.zip -OutFile cmake.zip
- cmd: echo "Unzipping cmake..."
- cmd: 7z x cmake.zip -o"C:\Program Files (x86)\" -y > nul
- cmd: set PATH=%PATH:CMake 2.8\bin=%;C:\Program Files (x86)\cmake-3.0.2-win32-x86\bin
- cmd: cmake --version
- cmd: echo "Downloading biicode..."
- ps: wget http://www.biicode.com/downloads/latest/win -OutFile bii-win.exe
- cmd: bii-win.exe /VERYSILENT
- cmd: set PATH=%PATH%;C:\Program Files (x86)\BiiCode\bii
- cmd: set project_name=xasti
- cmd: bii -v
- cmd: del bii-win.exe
- cmd: del cmake.zip
before_build:
- cmd: cd \
- cmd: bii init %project_name%
- cmd: cd %project_name%
- cmd: bii new svark/asti
# copy files and folders
- cmd: xcopy "%APPVEYOR_BUILD_FOLDER%" blocks\svark\asti\ /s
- cmd: bii find --update
- cmd: bii cpp:configure -G "Visual Studio 12"
- cmd: bii deps --detail
build_script:
- cmd: bii cpp:build
test_script:
- cmd: bii test
# to run your custom scripts instead of provider deployments
deploy_script:
on_success:
